// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Nuv_ArJME-rn3jzuC3HyIzJqVOjrr9E',
    appId: '1:1035419283102:web:643b5cfda4519055a4158f',
    messagingSenderId: '1035419283102',
    projectId: 'instagram-clone-44c68',
    authDomain: 'instagram-clone-44c68.firebaseapp.com',
    storageBucket: 'instagram-clone-44c68.appspot.com',
    measurementId: 'G-E33K1XD3F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtZRFiPVHo6-PyMPEHW0R6l8HDQX9Ajo',
    appId: '1:1035419283102:android:66ab58a8d776bc72a4158f',
    messagingSenderId: '1035419283102',
    projectId: 'instagram-clone-44c68',
    storageBucket: 'instagram-clone-44c68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHDZL8HrIQp80vIvUdk5eMpIGFjd3l-cE',
    appId: '1:1035419283102:ios:fa88b37aa3969a65a4158f',
    messagingSenderId: '1035419283102',
    projectId: 'instagram-clone-44c68',
    storageBucket: 'instagram-clone-44c68.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHDZL8HrIQp80vIvUdk5eMpIGFjd3l-cE',
    appId: '1:1035419283102:ios:fa88b37aa3969a65a4158f',
    messagingSenderId: '1035419283102',
    projectId: 'instagram-clone-44c68',
    storageBucket: 'instagram-clone-44c68.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Nuv_ArJME-rn3jzuC3HyIzJqVOjrr9E',
    appId: '1:1035419283102:web:058ff8ce9006cd6fa4158f',
    messagingSenderId: '1035419283102',
    projectId: 'instagram-clone-44c68',
    authDomain: 'instagram-clone-44c68.firebaseapp.com',
    storageBucket: 'instagram-clone-44c68.appspot.com',
    measurementId: 'G-LB38YPN7WC',
  );
}
